### ISSUE TITLE
fibonacci test should start from zero

### ISSUE THREAD

**Issue by teaddict** [wunderdogsw/typescript-training-e1#3]
https://github.com/wunderdogsw/typescript-training-e1/blob/17b64630961d552c1a291ec9b795e9824ef1b46a/test/session_one.test.ts#L66
current test expects `F(1) = 0`,
but actually it should be 
`F(0) = 0 , F(1) = 1`
so `const nth` can be removed, using the index solves the problem.

**Comment by villhei** [comment]
Unfortunately I can't recall what the decision leading to this indexing approach was based on, but I'd rather not break these tests at this point, as both variants of the indexing strategy are common enough in exercise suites such as this.

Good point though, this is a little bit on the grey area
