### ISSUE TITLE
Linter and formatter issue?

### ISSUE THREAD

**Issue by trungh13** [wunderdogsw/typescript-training-e1#4]
Hi, 
At first there are `"extends": ["tslint-config-airbnb", "typestrict"],` in `tslint.json` and we don't have `tslint-config-airbnb` in `package.json`. So by this way, it will throw error when you try to format with Prettier in VSCode. Should we add tslint-config-airbnb in devDependencies ?
Second, if you gonna install that package, there are few settings in `.prettierrc` which is 
`{
    "trailingComma": "es5",
    "tabWidth": 4,
    "semi": false,
    "singleQuote": true
}` which is conflict with `ts-config-airbnb` (I'm not really sure about ts-config-airbnb, but I used and setup with eslint-config-airbnb which default having some rules like tabWitdth:2, etc.). 
In the end, Prettier formatter confusing itself when seeing 2 files at the time. And it's not format it probably and popup errors even you use Prettier to format document.

**Comment by villhei** [comment]
Hey, the linter settings were (and are) still a little bit of a mess.

I added the `tslint-config-airbnb` and `tslint-config-prettier` and both `tslint` and `prettier` seem to work how I expect them to work (at least in my case). Had to fix a few errors and adjust the rules a bit. The 'tabWidth` should be enforced as 4 for both.

**Comment by trungh13** [comment]
What do you think about combining rule into one file tslint.json? 

Because Prettier have integration option with eslint and tslint in VSCode. So my suggestion is just giving all the overdriving rules over `tslint-config-airbnb` in tslint.json instead of .prettierrc. So both Linter(TSLint) and Formatter(Prettier) have same source/rule to do their job .

I added 2 more lines in my tslint.json & delete .prettierrc. No more conflict :D 
`"indent": [true, "spaces", 4],`
`"ter-indent": [true, 4, { "SwitchCase": 1 }],`

**Comment by villhei** [comment]
I'm closing this issue, instead of fixing the linter, it seems to be a better idea at this point to omit the linter rules from this repo, as tslint/eslint/prettier don't work well together at this very present moment
